export const SKILL_ALIAS_MAP = {
  // --- Backend & Server Aliases ---
  nodejs: "Node.js",
  node: "Node.js",
  expressjs: "Express",
  nest: "Nest.js",
  fastifyjs: "Fastify",
  hapi: "Hapi.js",
  spring: "Spring Boot",
  springboot: "Spring Boot",
  "python django": "Django",
  "python flask": "Flask",
  "fast api": "FastAPI",
  "laravel php": "Laravel",
  rails: "Ruby on Rails",
  ror: "Ruby on Rails",
  go: "Golang",
  "c#": "C#",
  cpp: "C++",
  py: "Python",
  php: "PHP",
  rest: "REST APIs",
  restapi: "REST APIs",
  grpc: "gRPC",
  microservice: "Microservices",
  websockets: "WebSockets",
  websocket: "WebSockets",
  "api gateway": "API Design", // API Design covers this concept
  authn: "Authentication",
  authz: "Authorization",
  loadbalancing: "Load Balancing",
  serverless: "Serverless",
  socketio: "Socket.io",
  kafka: "Kafka",
  rabbitmq: "RabbitMQ",
  amqp: "RabbitMQ",
  nats: "NATS",
  messagequeue: "Message Queues",

  // --- Frontend Aliases ---
  reactjs: "React",
  nextjs: "Next.js",
  remixjs: "Remix",
  angularjs: "Angular",
  vuejs: "Vue",
  nuxt: "Nuxt.js",
  sveltekit: "SvelteKit",
  jquery: "jQuery",
  tailwind: "Tailwind CSS",
  bootstrap: "Bootstrap",
  chakra: "Chakra UI",
  mui: "Material UI",
  styledcomponents: "Styled Components",
  typescript: "TypeScript",
  ts: "TypeScript",
  javascript: "JavaScript",
  js: "JavaScript",
  html: "HTML",
  css: "CSS",
  sass: "SASS",
  scss: "SASS",
  less: "LESS",
  webpack: "Webpack",
  parcel: "Parcel",
  rollup: "Rollup",
  babel: "Babel",
  storybook: "Storybook",
  threejs: "Three.js",
  webgl: "WebGL",

  // --- Databases Aliases ---
  postgres: "PostgreSQL",
  sql: "MySQL",
  mongo: "MongoDB",
  redis: "Redis",
  elastic: "Elasticsearch",
  firebase: "Firebase",
  dynamo: "DynamoDB",
  neo4j: "Neo4j",
  clickhouse: "ClickHouse",
  timescaledb: "TimescaleDB",
  snowflake: "Snowflake",
  bq: "BigQuery",
  couchdb: "CouchDB",

  // --- DevOps / Cloud Aliases ---
  k8s: "Kubernetes",
  tf: "Terraform",
  ci: "Jenkins", // A common CI tool, mapping to Jenkins as a representative
  gitlabci: "GitLab CI/CD",
  githubactions: "GitHub Actions",
  amazonwebservices: "AWS",
  gcp: "GCP",
  "google cloud": "GCP",
  do: "DigitalOcean",
  vercel: "Vercel",
  netlify: "Netlify",
  nginx: "Nginx",
  apache: "Apache",
  linux: "Linux",
  ubuntu: "Ubuntu",
  systemd: "Systemd",
  "ci/cd": "CI/CD",
  monitoring: "Monitoring",
  prom: "Prometheus",
  grafana: "Grafana",
  cloudformation: "CloudFormation",
  logging: "Logging",
  elk: "Elastic Stack (ELK)",
  kibana: "Kibana",
  cloudflare: "Cloudflare",
  argocd: "ArgoCD",

  // --- Data & ML Aliases ---
  ml: "Machine Learning",
  dl: "Deep Learning",
  ai: "AI",
  tf: "TensorFlow",
  pytorch: "PyTorch",
  sklearn: "Scikit-learn",
  pandas: "Pandas",
  numpy: "NumPy",
  matplotlib: "Matplotlib",
  seaborn: "Seaborn",
  nlp: "NLP",
  cv: "Computer Vision",
  dataeng: "Data Engineering",
  dbt: "DBT",
  airflow: "Airflow",
  hadoop: "Hadoop",
  spark: "Spark",
  "kafka streams": "Kafka Streams",
  "feature engineering": "Feature Engineering",
  mlops: "MLOps",
  "model deployment": "Model Deployment",
  jupyter: "Jupyter",
  colab: "Colab",
  "openai api": "OpenAI API",
  langchain: "LangChain",
  "data vis": "Data Visualization",

  // --- Security Aliases ---
  pentesting: "Penetration Testing",
  jwt: "JWT",
  oauth: "OAuth2",
  ssl: "SSL/TLS",
  firewall: "Firewall",
  siem: "SIEM",
  soc: "SOC",
  cybersecurity: "Cybersecurity",

  // --- Mobile Development Aliases ---
  rn: "React Native",
  flutter: "Flutter",
  swift: "Swift",
  "kotlin multiplatform": "Kotlin Multiplatform",
  android: "Android",
  ios: "iOS",
  xcode: "Xcode",
  "android studio": "Android Studio",
  "jetpack compose": "Jetpack Compose",
  fcm: "Firebase Cloud Messaging",

  // --- Testing / QA Aliases ---
  qa: "QA Automation",
  cypress: "Cypress",
  playwright: "Playwright",
  selenium: "Selenium",
  puppeteer: "Puppeteer",
  postman: "Postman",
  "e2e testing": "End-to-End Testing",
  "unit testing": "Unit Testing",
  "integration testing": "Integration Testing",
  "qa automation": "QA Automation",
  junit: "JUnit",

  // --- System Design / Architecture Aliases ---
  "sys design": "System Design",
  ha: "High Availability",
  ft: "Fault Tolerance",
  "distributed systems": "Distributed Systems",
  eda: "Event-Driven Architecture",
  cqrs: "CQRS",
  "event sourcing": "Event Sourcing",
  "api gateway": "API Gateway",
  "reverse proxy": "Reverse Proxy",
  "rate limiting": "Rate Limiting",
  "circuit breaker": "Circuit Breaker Pattern",

  // --- Analytics / Product Aliases ---
  ga: "Google Analytics",
  mixpanel: "Mixpanel",
  "ab testing": "A/B Testing",
  "product strategy": "Product Strategy",
  "user research": "User Research",

  // --- Tools / Version Control Aliases ---
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  bitbucket: "Bitbucket",
  vscode: "VS Code",
  intellij: "IntelliJ IDEA",
  jira: "JIRA",
  confluence: "Confluence",
  slack: "Slack",
  trello: "Trello",
  linear: "Linear",
  figma: "Figma",
  notion: "Notion",

  // --- Soft Skills / General Tech Aliases ---
  agile: "Agile",
  scrum: "Scrum",
  kanban: "Kanban",
  "devops culture": "DevOps Culture",
  "tech writing": "Technical Writing",
  documenation: "Documentation",
  mentoring: "Mentorship",
  "code review": "Code Review",
  "team lead": "Team Leadership",
  "problem solving": "Problem Solving",
  "critical thinking": "Critical Thinking",
  comms: "Communication",
};
